// ============================================
// Database Queries
// Neon PostgreSQL with Drizzle ORM
// ============================================

import { db } from "../db";
import { users, generatedContent, credits, contentTypeEnum } from "./schema";
import { eq, desc } from "drizzle-orm";
import { FREE_CREDITS } from "@/config/constants";

// --- Types ---
type ContentType = typeof contentTypeEnum.enumValues[number];

/**
 * Get a user by their Clerk ID.
 */
export async function getUserByClerkId(clerkId: string) {
  const result = await db
    .select()
    .from(users)
    .where(eq(users.clerkId, clerkId))
    .limit(1);
    
  return result[0] || null;
}

/**
 * Create a new user in the database (usually called from Clerk webhook).
 */
export async function createUser(data: {
  clerkId: string;
  email: string;
  name: string;
  imageUrl?: string;
}) {
  // 1. Create the user
  const newUser = await db.insert(users).values({
    clerkId: data.clerkId,
    email: data.email,
    name: data.name,
    imageUrl: data.imageUrl,
    subscriptionStatus: "free",
  }).returning();

  const user = newUser[0];

  // 2. Give free credits on signup
  await db.insert(credits).values({
    userId: user.id,
    amount: FREE_CREDITS,
    reason: "Signup bonus",
  });

  return user;
}

/**
 * Get total credits for a user.
 */
export async function getUserCredits(userId: string) {
  const transactions = await db
    .select({ amount: credits.amount })
    .from(credits)
    .where(eq(credits.userId, userId));

  // Sum all credit transactions
  return transactions.reduce((acc, curr) => acc + curr.amount, 0);
}

/**
 * Deduct credits from a user.
 */
export async function deductCredits(userId: string, amount: number, reason: string) {
  // Amount should be positive, we store it as negative
  await db.insert(credits).values({
    userId,
    amount: -Math.abs(amount),
    reason,
  });
}

/**
 * Save AI-generated content to the database.
 */
export async function saveGeneratedContent(data: {
  userId: string;
  type: ContentType;
  topic: string;
  content: unknown; // JSON object
}) {
  const newContent = await db.insert(generatedContent).values({
    userId: data.userId,
    type: data.type,
    topic: data.topic,
    content: data.content,
  }).returning();

  return newContent[0];
}

/**
 * Get all content generated by a user.
 */
export async function getUserContent(userId: string) {
  return db
    .select()
    .from(generatedContent)
    .where(eq(generatedContent.userId, userId))
    .orderBy(desc(generatedContent.createdAt));
}

/**
 * Get a specific content item by its ID.
 */
export async function getContentById(id: string) {
  const result = await db
    .select()
    .from(generatedContent)
    .where(eq(generatedContent.id, id))
    .limit(1);
    
  return result[0] || null;
}
