"use client";
import React from "react";
import { Document, Page, Text, View, StyleSheet, Font } from "@react-pdf/renderer";

// Registered standard fonts
const styles = StyleSheet.create({
  page: {
    padding: 40,
    backgroundColor: "#ffffff",
  },
  title: {
    fontSize: 24,
    marginBottom: 20,
    fontWeight: "bold",
    color: "#1e293b",
    textAlign: "center",
  },
  section: {
    marginBottom: 15,
  },
  heading: {
    fontSize: 18,
    marginBottom: 8,
    color: "#2563eb",
    fontWeight: "bold",
  },
  content: {
    fontSize: 12,
    lineHeight: 1.6,
    color: "#4b5563",
    textAlign: "justify",
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: "center",
    fontSize: 10,
    color: "#9ca3af",
  },
});

interface PDFDocumentProps {
  title: string;
  sections: Array<{ heading: string; content: string }>;
}

/**
 * Standard PDF Template for Study Notes & Materials
 */
const PDFDocument: React.FC<PDFDocumentProps> = ({ title, sections }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <Text style={styles.title}>{title}</Text>
      
      {sections.map((section, index) => (
        <View key={index} style={styles.section}>
          <Text style={styles.heading}>{section.heading}</Text>
          <Text style={styles.content}>{section.content}</Text>
        </View>
      ))}

      <Text style={styles.footer} render={({ pageNumber, totalPages }) => (
        `Generated by Examination Platform - Page ${pageNumber} of ${totalPages}`
      )} fixed />
    </Page>
  </Document>
);

export default PDFDocument;
